### ISSUE TITLE
Crashing on none found songs in spotify & threads above 6

### ISSUE THREAD

**Issue by XtremeForce** [WilliamSchack/Spotify-Downloader#11]
the program crashes when searching for songs that is not found in spotify ana crashes on any threads above 6 ![image](https://github.com/user-attachments/assets/3c012171-41ff-450a-89ae-dff343bd28a6)

**Comment by WilliamSchack** [comment]
That's strange I have put things into place to account for those songs but I may have broken it some how, or these songs need to be handled differently. I will also have a look into the thread problem too, I have not done much debugging accounting for higher threads but I may as well fix this and look into more bugs as well, try and fix as many high thread count issues as I can

**Comment by WilliamSchack** [comment]
So I have tried with songs from my playlist that are not on spotify anymore (as I cannot see yours on spotify), and they work fine, as well as having the threads above 6. Were you downloading the whole playlist on above 6 threads and it didn't work? How many threads did you use specifically or did you just try a few above 6? I have tried downloading your playlist again and no issues on my side.

I have been meaning to do this but I will implement crash logs and send through a version with them when it is done and get the log from your pc just to get the issue in case I cannot still replicate it on my machine

**Comment by WilliamSchack** [comment]
So I have implemented a log to the program just to make debugging these issues easier, would you please be able to [download this version](https://drive.google.com/file/d/1vYfDjPXwUNHNe8O612HXD5JkS1jNG0_D) (https://drive.google.com/file/d/1vYfDjPXwUNHNe8O612HXD5JkS1jNG0_D) (had to upload it to drive, file is too large), open SpotifyDownloader.exe, and run your download as you did before with the crash?

After the application crashes, would you please be able to navigate to "%temp%/SpotifyDownloader" (C:/User/Appdata/Local/Temp/SpotifyDownloader) and send Log.log here

Hopefully this tells me your issue as I cannot replicate it on my machine, its always a bit annoying having to debug this stuff but we can do it

**Comment by XtremeForce** [comment]
> So I have implemented a log to the program just to make debugging these issues easier, would you please be able to [download this version](https://drive.google.com/file/d/1vYfDjPXwUNHNe8O612HXD5JkS1jNG0_D) (https://drive.google.com/file/d/1vYfDjPXwUNHNe8O612HXD5JkS1jNG0_D) (had to upload it to drive, file is too large), open SpotifyDownloader.exe, and run your download as you did before with the crash?
> 
> 
> 
> After the application crashes, would you please be able to navigate to "%temp%/SpotifyDownloader" (C:/User/Appdata/Local/Temp/SpotifyDownloader) and send Log.log here
> 
> 
> 
> Hopefully this tells me your issue as I cannot replicate it on my machine, its always a bit annoying having to debug this stuff but we can do it

ok i will try

**Comment by XtremeForce** [comment]
[Log.log](https://github.com/user-attachments/files/16480807/Log.log)
this is for running at thread = 6

**Comment by XtremeForce** [comment]
[Log.log](https://github.com/user-attachments/files/16480855/Log.log)
this for downloading normally at thread 5

**Comment by WilliamSchack** [comment]
Thats strange there doesnt seem to be any error at the end making it crash but I have noticed that in both of the logs it starts downloading before the thread is ready, so I will try and fix that and do some more tests replicating your settings.

I also see a song in the downloads that shows up as null, that is most likely those songs that aren't on spotify so I will put a check in place for those and see if that works. If this is the reason, it makes sense why 6 threads crashes the program because it puts this null song at the start of the list, downloading it first but with 5 threads it will be downloaded later on

**Comment by WilliamSchack** [comment]
Yep those songs are the culprit shouldn't take too long to fix

**Comment by WilliamSchack** [comment]
Fixed in commit https://github.com/WilliamSchack/Spotify-Downloader/commit/a6db19fec53cfdf39a17faa2408617c3ade10aaf and will be released soon :)

**Comment by WilliamSchack** [comment]
Released into version [1.4.2](https://github.com/WilliamSchack/Spotify-Downloader/releases/tag/v1.4.2)

**Comment by XtremeForce** [comment]
> Fixed in commit [a6db19f](https://github.com/WilliamSchack/Spotify-Downloader/commit/a6db19fec53cfdf39a17faa2408617c3ade10aaf) and will be released soon :)

i have tried running it now and it worked properly without any crashes or interuptions 
thank you for fixing it and for making this wonderful program <3

**Comment by WilliamSchack** [comment]
> i have tried running it now and it worked properly without any crashes or interuptions thank you for fixing it and for making this wonderful program <3

Glad I could help and thanks for helping me find issues and improve the program :)
