### ISSUE TITLE
Feature Request: PASTE URL Button

### ISSUE THREAD

**Issue by rodriguezrobinj** [WilliamSchack/Spotify-Downloader#14]
It would be a good thing if there was a button to directly paste the URL to the text box, without having to resort to the classic ctrl+v or right click and paste, but directly a button to paste immediately, something like that.

 ![image](https://github.com/user-attachments/assets/5df60f89-402a-49cf-ae96-41cfc7b2fc30)

Taking the YT SAVER program as an example

![image](https://github.com/user-attachments/assets/cde23484-eac6-4064-af41-37e6f8e6f927)

**Comment by WilliamSchack** [comment]
To be completely fair I have been looking for something to replace where the old settings button was to make it aligned and nice and I don't know how I havent thought of this thanks I will definitely put this in

**Comment by WilliamSchack** [comment]
Just added in commit cdb536b I will close this issue once its released

I am still testing the changes to the search algorithm so it may be a few days before this release
