### ISSUE TITLE
Bug with normalizing sound option.

### ISSUE THREAD

**Issue by swordBoi13** [WilliamSchack/Spotify-Downloader#20]
Firs of all, I'm really grateful for such an amazing application, and I'd love to promote this, but I fear that it might get striked, so yeah. When we select the normalizing sound option, it is set to 14db, when it should be set to -14. This has to be changed manually, but people who don't know might just download an entire playlist without know this. This is the only bug I found, really amazing app, thanks.

**Comment by WilliamSchack** [comment]
HOLY CRAP HOW THE HELL DID I LET THIS ONE SLIP THROUGH

Looking at the commits this has been in the app since 5 months ago im surprised myself or no one else has found this

Just one simple minus sign to ruin it all

I cannot thank you enough I will get on this one as soon as I can 🙏

**Comment by WilliamSchack** [comment]
Someone else had an issue this morning about distorted audio that I had no clue what it was but this is 100% the issue perfect timing

Im just gonna say this for you and if anyone else sees this issue I am sorry for bursting off your ears

**Comment by WilliamSchack** [comment]
Just released into [v1.5.2](https://github.com/WilliamSchack/Spotify-Downloader/releases/tag/v1.5.2)

I cannot thank you enough for finding this there is no way I would have found it otherwise
