### ISSUE TITLE
non responding

### ISSUE THREAD

**Issue by mailmefren** [WilliamSchack/Spotify-Downloader#21]
App is stocked at "Getting Playlist Data..." Any idea? Thank in advance.

**Comment by WilliamSchack** [comment]
There can be multiple reasons to why this is happening but hopefully we can walk through it any figure it out

My first thought, if you are using a large playlist and your internet speed is a bit slower it may take a while to compile all of the songs from spotify, so try it with maybe one song or a smaller playlist and see if it works (I am sure that this is not the issue but good to test it anyway)

The title of the issue says non responding so does the app stop responding? Or is it just as you say where it just doesn't progress to the next part

Can you start the download again where it gets stuck at "Getting Playlist Data..." and close the app after its stuck for a bit then send the log through located at (%temp%/SpotifyDownloader/Log.log) that will help me determine the issue a lot easier

**Comment by mailmefren** [comment]
Here is log


21-10-2024 19:50:29 |   Info   | 10 | main.cpp | main | RUNNING VERSION 1.5.1
21-10-2024 19:50:29 |   Info   | 195 | SpotifyDownloader.cpp | LoadSettings | Settings Successfully Loaded QJsonObject({"Audio Bitrate":256,"Download Speed Limit":0,"Downloader Threads":6,"Folder Sorting Index":0,"Normalise Enabled":false,"Normalise Volume":15,"Overwrite Enabled":false,"Song Output Format":"<Song Name> - <Song Artist>","Song Output Format Tag":"<>","Status Notifications Enabled":true})
21-10-2024 19:50:29 |   Info   | 57 | SpotifyDownloader.cpp | SetupDownloaderThread | Successfully Setup Playlist Worker Thread
21-10-2024 19:50:29 |   Info   | 32 | SpotifyDownloader.cpp | SpotifyDownloader | Successfully Initialised
21-10-2024 19:52:07 |   Info   | 185 | UISetup.cpp | ) | Starting download for playlist "https://open.spotify.com/track/3v3LCxSS3dqlhQMIR9BOkT?si=5b289b544aac4ac5"
21-10-2024 19:52:07 |   Info   | 422 | PlaylistDownloader.cpp | ClearDirFiles | Cleaned directory: "C:/Users/niran/AppData/Local/Temp/SpotifyDownloader/Downloading"
21-10-2024 19:52:09 | Warning  | 105 | PlaylistDownloader.cpp | DownloadSongs | 0 Songs passed check from spotify playlist. Songs are probably already downloaded
21-10-2024 19:52:09 | Warning  | 0 |  |  | QSystemTrayIcon::showMessage: Wrong icon size (72x72), please add standard one: 48x48
21-10-2024 19:52:09 |   Info   | 319 | PlaylistDownloader.cpp | ~PlaylistDownloader | Playlist Downloader Quitting
21-10-2024 19:52:09 |   Info   | 57 | SpotifyDownloader.cpp | SetupDownloaderThread | Successfully Setup Playlist Worker Thread
21-10-2024 19:52:09 |   Info   | 422 | PlaylistDownloader.cpp | ClearDirFiles | Cleaned directory: "C:/Users/niran/AppData/Local/Temp/SpotifyDownloader/Cover Art"
21-10-2024 19:52:09 |   Info   | 422 | PlaylistDownloader.cpp | ClearDirFiles | Cleaned directory: "C:/Users/niran/AppData/Local/Temp/SpotifyDownloader/Downloading"
21-10-2024 19:52:09 |   Info   | 356 | PlaylistDownloader.cpp | ~PlaylistDownloader | Downloads complete with no errors
21-10-2024 19:52:09 | Warning  | 0 |  |  | QSystemTrayIcon::showMessage: Wrong icon size (72x72), please add standard one: 48x48
21-10-2024 19:53:06 |   Info   | 185 | UISetup.cpp | ) | Starting download for playlist "https://open.spotify.com/track/3v3LCxSS3dqlhQMIR9BOkT?si=5b289b544aac4ac5"
21-10-2024 19:53:06 |   Info   | 422 | PlaylistDownloader.cpp | ClearDirFiles | Cleaned directory: "C:/Users/niran/AppData/Local/Temp/SpotifyDownloader/Downloading"
21-10-2024 19:53:07 | Warning  | 105 | PlaylistDownloader.cpp | DownloadSongs | 0 Songs passed check from spotify playlist. Songs are probably already downloaded
21-10-2024 19:53:07 | Warning  | 0 |  |  | QSystemTrayIcon::showMessage: Wrong icon size (72x72), please add standard one: 48x48
21-10-2024 19:53:07 |   Info   | 319 | PlaylistDownloader.cpp | ~PlaylistDownloader | Playlist Downloader Quitting
21-10-2024 19:53:07 |   Info   | 57 | SpotifyDownloader.cpp | SetupDownloaderThread | Successfully Setup Playlist Worker Thread
21-10-2024 19:53:07 |   Info   | 422 | PlaylistDownloader.cpp | ClearDirFiles | Cleaned directory: "C:/Users/niran/AppData/Local/Temp/SpotifyDownloader/Cover Art"
21-10-2024 19:53:07 |   Info   | 422 | PlaylistDownloader.cpp | ClearDirFiles | Cleaned directory: "C:/Users/niran/AppData/Local/Temp/SpotifyDownloader/Downloading"
21-10-2024 19:53:07 |   Info   | 356 | PlaylistDownloader.cpp | ~PlaylistDownloader | Downloads complete with no errors

**Comment by WilliamSchack** [comment]
So you have your settings setup a bit strange especially the naming format so if you change the following settings it should work fine. I will also say to change the audio normalisation down to -14db to fix a few audio distortion errors

Naming Format: FROM "-" TO "<Song Name> - <Artist Name>"
Normalize Volume: FROM "15db" TO "-14db"

You have your song output format as "-" which no matter the song is creating a file with that name, so it starts, sees that you already have a file called "-.mp3" and then cancels the download because you have overwrite disabled

It also seems like there is another error with the icon size when showing a notification so I will look into that. If you change the previous settings and it still doesn't work, try disabling Show Status Notifications in the downloading tab and see if that fixes it

Let me know if changing those settings fix the issue :)
