### ISSUE TITLE
Feature Request: Be able to manipulate the order in which songs are named by tags at download time

### ISSUE THREAD

**Issue by rodriguezrobinj** [WilliamSchack/Spotify-Downloader#5]
It would be good if you could configure how the songs will be named at the time they are downloaded, in order to not always have the format of %Song Name% - %Artist%.

 ![image](https://github.com/WilliamSchack/Spotify-Downloader/assets/108781192/94bc368b-b924-46af-9794-2919b6a1e01a)

 If you want it to only have the format of %Song Name% or if you want a more complete format, simply configure the naming tags %Song Name% - %Artist%

 ![image](https://github.com/WilliamSchack/Spotify-Downloader/assets/108781192/ce44c5d7-addb-48e1-94ae-404d70785610)

**Comment by WilliamSchack** [comment]
This is actually a pretty good request and probably a needed one as well for some, I just never considered it. I will definitely set this up in a future update thanks for the request!

**Comment by WilliamSchack** [comment]
Just implemented this feature into the [latest commit](https://github.com/WilliamSchack/Spotify-Downloader/commit/3b0cf68c1f6823356d0917e90b8bd0c13c74f52e), you can now change the output name of the files and I decided to add a fair amount of tags to customise the name even further!

Thanks for the feature request and hope it helps :)

**Comment by WilliamSchack** [comment]
This is now released into [v1.3.0](https://github.com/WilliamSchack/Spotify-Downloader/releases/tag/v1.3.0) :)
