### ISSUE TITLE
Feature Request: Organized download of songs through folders according to artists, album, etc.

### ISSUE THREAD

**Issue by rodriguezrobinj** [WilliamSchack/Spotify-Downloader#7]
This is something more to my personal taste, but it would be nice if when the songs are downloaded they would be automatically organized into folders according to artist(s), album, etc.

 ![image](https://github.com/WilliamSchack/Spotify-Downloader/assets/108781192/e1feba92-f3e1-4d83-ac36-e5e65d607cb8)

In order to have everything more organized, and so it can be made easier to search for the songs I want to listen to according to my favorite artists (This is something to my personal taste).

#4 , something like with tags, but in this case as a folder organizer, so as not to have all the songs scattered around in the same folder.

**Comment by WilliamSchack** [comment]
This is not a bad idea and ill definitely implement it soon
Always good to have more organisation

**Comment by WilliamSchack** [comment]
Just implemented this into https://github.com/WilliamSchack/Spotify-Downloader/commit/f30f568e5560bacd2d3e96279b7d1b916eefbb88 should have it released within the hour :)

**Comment by WilliamSchack** [comment]
Released into [v1.4.0](https://github.com/WilliamSchack/Spotify-Downloader/releases/tag/v1.4.0) :)
