### ISSUE TITLE
Feature Request: After downloading the song and returning to the main screen this appears with empty text input

### ISSUE THREAD

**Issue by rodriguezrobinj** [WilliamSchack/Spotify-Downloader#8]
Something that seems as simple as simply deleting the entry for the link of the song or play, it is tedious to have to empty that entry every time the song download is finished.

 At the moment:

 ![image](https://github.com/WilliamSchack/Spotify-Downloader/assets/108781192/4edd55c2-9675-4029-b89f-cb737fd80df0)

 It could be:

 ![image](https://github.com/WilliamSchack/Spotify-Downloader/assets/108781192/f9c114df-7f0d-40ec-86a1-02c51a7dfead)

**Comment by WilliamSchack** [comment]
I actually didnt realise it was doing this I never payed too much attention but this wasn't specifically written in the code so ill have to have a look into it. Ill release it in a hotfix soon

**Comment by WilliamSchack** [comment]
Sorry been busy the past week just started on it and realised I misunderstood the question my bad :/
Its been changed to remove the playlist url now XD

**Comment by WilliamSchack** [comment]
Released into [v1.4.0](https://github.com/WilliamSchack/Spotify-Downloader/releases/tag/v1.4.0) :)
